[package]
name = "g6-cli"
version = "0.0.3"
edition = "2021"
description = "CLI tool for controlling the SoundBlaster X G6 on Windows"
license = "GPL-2.0-only"

[lib]
name = "g6_cli"
path = "src/lib.rs"

[[bin]]
name = "g6-cli"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
hidapi = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"

[profile.release]
strip = true
lto = true
